I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 676, in script
    show jorunn glee at moreright with goup
  File "game/script.rpy", line 676, in <module>
    show jorunn glee at moreright with goup
NameError: name 'goup' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 676, in script
    show jorunn glee at moreright with goup
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1359, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\kansa\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 676, in <module>
    show jorunn glee at moreright with goup
NameError: name 'goup' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
HeartsDepth 1.0
Mon Jul  1 03:04:06 2024
